<?php

namespace common\models;

use Yii;
use yii\helpers\Html;
use yii\web\UploadedFile;

/**
 * This is the model class for table "carousel".
 *
 * @property integer $id
 * @property string $image
 * @property string $caption
 */
class Carousel extends \yii\db\ActiveRecord
{
    public $file;
    public static $height = '256px';
    public static $width = '100%';

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'carousel';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id'], 'integer'],
            [['image', 'name'], 'string', 'max' => 50],
            [['caption'], 'string', 'max' => 150],
            [['file'], 'image'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название слайда',
            'image' => 'Изображение',
            'caption' => 'Текст',
        ];
    }

    public function beforeSave($insert)
    {
        if ($file = UploadedFile::getInstance($this, 'file')) {
            $this->image = strtotime('NOW') . '.' . $file->extension;
            $file->saveAs(Yii::getAlias('@dir_images') . '/' . $this->image);
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public static function getSlides()
    {
        $slides = self::find()->all();
        $items = [];
        $a = [];

        foreach ($slides as $slide) {
            $items ['content'] = Html::img(Yii::getAlias('@images').'/'.$slide['image'], ['style' => 'height: '.self::$height.'; width: '.self::$width.'']);
            $items ['caption'] = $slide['caption'];
            array_push($a, $items);
        }
        return $a;
    }
}
