<?php

namespace common\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "product_variation".
 *
 * @property integer $id
 * @property integer $product_id
 * @property integer $variation_id
 * @property string $price
 * @property string $sku
 * @property string $image
 * @property integer $quantity
 * @property integer $stock_status_id
 */
class ProductVariation extends \yii\db\ActiveRecord
{
    public $product;
    public $file;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'product_variation';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['product_id', 'variation_id', 'quantity', 'stock_status_id'], 'integer'],
            [['price'], 'number'],
            [['product'], 'safe'],
            [['image'], 'string', 'max' => 255],
            [['sku'], 'string', 'max' => 20],
            [['file'], 'image'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'product_id' => 'Product ID',
            'variation_id' => 'Вариация',
            'price' => 'Цена',
            'quantity' => 'Количество',
            'stock_status_id' => 'Статус',
            'sku' => 'Артикул',
            'file' => 'Изображение',
        ];
    }

    public function beforeSave($insert)
    {
        if ($file = UploadedFile::getInstance($this, 'file')) {
            $this->image = strtotime('now') . "." . $file->extension;
            $file->saveAs(Yii::getAlias("@dir_images") . "/" . $this->image);
        }


        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function beforeDelete()
    {
        //unlink(Yii::getAlias('@dir_images').'/'.$this->image);

        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function getName() {
        return $this->hasOne(Variation::className(), ['id' => 'variation_id']);
    }
}
